# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: efe0c1c0290052397fd8789805ef870ad2d910f934d9f7f464f2d89eed2a993a62322deda76da252a9b6899b9f621cc2f1213b7f79678a3312c4794e3ba763ab

test:
  secret_key_base: 460cceffcdbcab0d638f52e84947e9b59684c357fe490449c84c5c28002e01c0cfaacf25e25c89b43f2d6ce8713b9fdffbed501667167b2294f1adecd0690423

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
